version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run:
          name: 'Set up prod environments'
          command: |
            node scripts/set-up-config.js $omdbApiKey $firebaseApiKey $firebaseAuthDomain $firebaseDatabaseURL $firebaseProjectId $firebaseStorageBucket $firebaseMessagingSenderId $firebaseAppId $firebaseMeasurementId $firebaseUrl

workflows:
    build-and-test:
      jobs:
        - build-and-test